#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Sat Apr 17 19:51:02 2010

import wx
import wx.grid

# begin wxGlade: extracode
# end wxGlade



class MainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        
        # Menu Bar
        self.menu = wx.MenuBar()
        self.file_menu = wx.Menu()
        self.mergeDB_button = wx.MenuItem(self.file_menu, 1020, "Merge With Database", "Merge another database file with this one", wx.ITEM_NORMAL)
        self.file_menu.AppendItem(self.mergeDB_button)
        self.file_menu.AppendSeparator()
        self.quit_button = wx.MenuItem(self.file_menu, 1030, "Quit", "Quit the program", wx.ITEM_NORMAL)
        self.file_menu.AppendItem(self.quit_button)
        self.menu.Append(self.file_menu, "File")
        self.SetMenuBar(self.menu)
        # Menu Bar end
        self.entry_list = wx.grid.Grid(self, -1, size=(1, 1))
        self.new_button = wx.Button(self, wx.ID_NEW, "")
        self.delete_button = wx.Button(self, wx.ID_DELETE, "")
        self.label_1 = wx.StaticText(self, -1, "University ID")
        self.university_ID_box = wx.TextCtrl(self, -1, "")
        self.label_2 = wx.StaticText(self, -1, "Name (First Last)")
        self.name_box = wx.TextCtrl(self, -1, "")
        self.label_3 = wx.StaticText(self, -1, "Email Address")
        self.email_address_box = wx.TextCtrl(self, -1, "")
        self.label_4 = wx.StaticText(self, -1, "Paid Member")
        self.paid_member_box = wx.CheckBox(self, -1, "Paid")
        self.mailing_lists = wx.CheckListBox(self, -1, style=wx.LC_REPORT|wx.SUNKEN_BORDER)
        self.main_frame_statusbar = self.CreateStatusBar(1, 0)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_MENU, self.mergeDB_button_clicked, self.mergeDB_button)
        self.Bind(wx.EVT_MENU, self.quit_button_clicked, self.quit_button)
        self.Bind(wx.EVT_BUTTON, self.new_button_clicked, self.new_button)
        self.Bind(wx.EVT_BUTTON, self.delete_button_clicked, self.delete_button)
        self.Bind(wx.EVT_TEXT_ENTER, self.university_ID_box_enter, self.university_ID_box)
        self.Bind(wx.EVT_TEXT, self.university_ID_box_change, self.university_ID_box)
        self.Bind(wx.EVT_TEXT_ENTER, self.name_box_enter, self.name_box)
        self.Bind(wx.EVT_TEXT, self.name_box_change, self.name_box)
        self.Bind(wx.EVT_TEXT_ENTER, self.email_address_box_enter, self.email_address_box)
        self.Bind(wx.EVT_TEXT, self.email_address_box_change, self.email_address_box)
        self.Bind(wx.EVT_CHECKBOX, self.paid_member_box_clicked, self.paid_member_box)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainFrame.__set_properties
        self.SetTitle("FuseUp")
        self.SetSize((617, 423))
        self.entry_list.CreateGrid(2, 5)
        self.entry_list.SetRowLabelSize(0)
        self.entry_list.EnableEditing(0)
        self.entry_list.EnableDragRowSize(0)
        self.entry_list.SetSelectionMode(wx.grid.Grid.wxGridSelectRows)
        self.entry_list.SetColLabelValue(0, "University ID")
        self.entry_list.SetColLabelValue(1, "Name")
        self.entry_list.SetColLabelValue(2, "Email")
        self.entry_list.SetColLabelValue(3, "Paid")
        self.entry_list.SetColLabelValue(4, "Subscriptions")
        self.main_frame_statusbar.SetStatusWidths([-1])
        # statusbar fields
        main_frame_statusbar_fields = ["0 Registered (0 Paid)"]
        for i in range(len(main_frame_statusbar_fields)):
            self.main_frame_statusbar.SetStatusText(main_frame_statusbar_fields[i], i)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainFrame.__do_layout
        main_sizer = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.FlexGridSizer(3, 1, 0, 0)
        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_2 = wx.FlexGridSizer(4, 2, 0, 0)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_1.Add(self.entry_list, 1, wx.EXPAND, 0)
        sizer_2.Add(self.new_button, 0, 0, 0)
        sizer_2.Add(self.delete_button, 0, 0, 0)
        sizer_2.Add((20, 2), 1, wx.EXPAND, 0)
        grid_sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
        grid_sizer_2.Add(self.label_1, 0, 0, 0)
        grid_sizer_2.Add(self.university_ID_box, 0, wx.EXPAND, 0)
        grid_sizer_2.Add(self.label_2, 0, 0, 0)
        grid_sizer_2.Add(self.name_box, 0, wx.EXPAND, 0)
        grid_sizer_2.Add(self.label_3, 0, 0, 0)
        grid_sizer_2.Add(self.email_address_box, 0, wx.EXPAND, 0)
        grid_sizer_2.Add(self.label_4, 0, 0, 0)
        grid_sizer_2.Add(self.paid_member_box, 0, wx.EXPAND, 0)
        grid_sizer_2.AddGrowableCol(1)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)
        sizer_1.Add(self.mailing_lists, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(sizer_1, 2, wx.EXPAND, 0)
        grid_sizer_1.AddGrowableRow(0)
        grid_sizer_1.AddGrowableRow(2)
        grid_sizer_1.AddGrowableCol(0)
        main_sizer.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        self.SetSizer(main_sizer)
        self.Layout()
        # end wxGlade

    def mergeDB_button_clicked(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `mergeDB_button_clicked' not implemented!"
        event.Skip()

    def quit_button_clicked(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `quit_button_clicked' not implemented!"
        event.Skip()

    def new_button_clicked(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `new_button_clicked' not implemented!"
        event.Skip()

    def delete_button_clicked(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `delete_button_clicked' not implemented!"
        event.Skip()

    def university_ID_box_enter(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `university_ID_box_enter' not implemented!"
        event.Skip()

    def university_ID_box_change(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `university_ID_box_change' not implemented!"
        event.Skip()

    def name_box_enter(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `name_box_enter' not implemented!"
        event.Skip()

    def name_box_change(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `name_box_change' not implemented!"
        event.Skip()

    def email_address_box_enter(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `email_address_box_enter' not implemented!"
        event.Skip()

    def email_address_box_change(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `email_address_box_change' not implemented!"
        event.Skip()

    def paid_member_box_clicked(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `paid_member_box_clicked' not implemented!"
        event.Skip()

# end of class MainFrame


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    main_frame = MainFrame(None, -1, "")
    app.SetTopWindow(main_frame)
    main_frame.Show()
    app.MainLoop()
